/*
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * plugin_id.h
 * Contains the plugin ids.
 * Copyright (C) 2005-2009 Simon Newton
 *
 * This file has been autogenerated by make_plugin_id.sh, DO NOT EDIT.
 */

#ifndef INCLUDE_OLA_PLUGIN_ID_H_
#define INCLUDE_OLA_PLUGIN_ID_H_

namespace ola {

typedef enum {
  OLA_PLUGIN_ALL = 0,
  OLA_PLUGIN_DUMMY = 1,
  OLA_PLUGIN_ARTNET = 2,
  OLA_PLUGIN_SHOWNET = 3,
  OLA_PLUGIN_ESPNET = 4,
  OLA_PLUGIN_USBPRO = 5,
  OLA_PLUGIN_OPENDMX = 6,
  OLA_PLUGIN_SANDNET = 7,
  OLA_PLUGIN_STAGEPROFI = 8,
  OLA_PLUGIN_PATHPORT = 9,
  OLA_PLUGIN_DMX4LINUX = 10,
  OLA_PLUGIN_E131 = 11,
  OLA_PLUGIN_USBDMX = 12,
  OLA_PLUGIN_FTDIDMX = 13,
  OLA_PLUGIN_OSC = 14,
  OLA_PLUGIN_SPI = 15,
  OLA_PLUGIN_KINET = 16,
  OLA_PLUGIN_KARATE = 17,
  OLA_PLUGIN_MILINST = 18,
  OLA_PLUGIN_RENARD = 19,
  OLA_PLUGIN_EXPERIMENTAL = 10000,
} ola_plugin_id;
}  // namespace ola
#endif  // INCLUDE_OLA_PLUGIN_ID_H_
